from module.atom.image import RuleImage
from module.atom.click import RuleClick
from module.atom.long_click import RuleLongClick
from module.atom.swipe import RuleSwipe
from module.atom.ocr import RuleOcr
from module.atom.list import RuleList

# This file was automatically generated by ./dev_tools/assets_extract.py.
# Don't modify it manually.
class ChessAssets: 


	# Click Rule Assets
	# 商店式神5 
	C_SHIKIGAMI_5 = RuleClick(roi_front=(350,61,167,140), roi_back=(350,61,167,140), name="shikigami_5")
	# 商店式神4 
	C_SHIKIGAMI_4 = RuleClick(roi_front=(537,61,167,140), roi_back=(537,61,167,140), name="shikigami_4")
	# 商店式神3 
	C_SHIKIGAMI_3 = RuleClick(roi_front=(724,61,167,140), roi_back=(724,61,167,140), name="shikigami_3")
	# 商店式神2 
	C_SHIKIGAMI_2 = RuleClick(roi_front=(911,61,167,140), roi_back=(911,61,167,140), name="shikigami_2")
	# 商店式神1 
	C_SHIKIGAMI_1 = RuleClick(roi_front=(1098,61,167,140), roi_back=(1098,61,167,140), name="shikigami_1")
	#  
	C_SHIKIGAMI_STORE = RuleClick(roi_front=(344,55,925,241), roi_back=(344,55,925,241), name="shikigami_store")
	# Buff左侧选项卡面 
	C_BUFF_OPTION_1 = RuleClick(roi_front=(320,205,90,130), roi_back=(320,205,90,130), name="buff_option_1")
	# Buff中间选项卡面 
	C_BUFF_OPTION_2 = RuleClick(roi_front=(598,205,90,130), roi_back=(598,205,90,130), name="buff_option_2")
	# Buff右侧选项卡面 
	C_BUFF_OPTION_3 = RuleClick(roi_front=(875,205,90,130), roi_back=(875,205,90,130), name="buff_option_3")
	# 关闭式神详情界面 
	C_CLICK_CLOSE_SPECIFICS_AREA = RuleClick(roi_front=(193,95,91,430), roi_back=(193,95,91,430), name="click_close_specifics_area")


	# Image Rule Assets
	# 回大厅 
	I_EXIT_TO_CHESS = RuleImage(roi_front=(384,591,172,47), roi_back=(340,570,270,100), threshold=0.8, method="Template matching", file="./tasks/Chess/c/c_exit_to_chess.png")
	# 分享 
	I_SHARE = RuleImage(roi_front=(1138,560,107,113), roi_back=(1138,560,107,113), threshold=0.8, method="Template matching", file="./tasks/Chess/c/c_share.png")
	# 选buff环节 
	I_SELECT_BUFF = RuleImage(roi_front=(533,74,218,43), roi_back=(533,74,218,43), threshold=0.8, method="Template matching", file="./tasks/Chess/c/c_select_buff.png")
	#  
	I_CHESS_START = RuleImage(roi_front=(1159,595,65,66), roi_back=(1159,595,65,66), threshold=0.8, method="Template matching", file="./tasks/Chess/c/c_chess_start.png")
	#  
	I_EXIT_TO_CHESS_2 = RuleImage(roi_front=(580,593,123,43), roi_back=(580,593,123,43), threshold=0.8, method="Template matching", file="./tasks/Chess/c/c_exit_to_chess_2.png")
	#  
	I_CHECK_RANK = RuleImage(roi_front=(14,75,79,38), roi_back=(14,75,79,38), threshold=0.8, method="Template matching", file="./tasks/Chess/c/c_check_rank.png")
	#  
	I_RANK_GOTO_CHESS = RuleImage(roi_front=(66,646,133,42), roi_back=(66,646,133,42), threshold=0.8, method="Template matching", file="./tasks/Chess/c/c_rank_goto_chess.png")
	#  
	I_USE_SOUL = RuleImage(roi_front=(1005,144,172,47), roi_back=(1005,144,172,47), threshold=0.8, method="Template matching", file="./tasks/Chess/c/c_use_soul.png")
	#  
	I_SELECT_SOUL_1 = RuleImage(roi_front=(390,326,70,35), roi_back=(390,326,70,35), threshold=0.8, method="Template matching", file="./tasks/Chess/c/c_select_soul_1.png")
	#  
	I_SELECT_SOUL_2 = RuleImage(roi_front=(605,326,70,35), roi_back=(605,326,70,35), threshold=0.8, method="Template matching", file="./tasks/Chess/c/c_select_soul_2.png")
	#  
	I_SELECT_SOUL_3 = RuleImage(roi_front=(821,327,70,35), roi_back=(821,327,70,35), threshold=0.8, method="Template matching", file="./tasks/Chess/c/c_select_soul_3.png")
	# 商店 
	I_MARKET = RuleImage(roi_front=(1159,614,89,26), roi_back=(1159,614,89,26), threshold=0.8, method="Template matching", file="./tasks/Chess/c/c_market.png")
	# 购买经验 
	I_EXPERIENCE = RuleImage(roi_front=(37,641,102,26), roi_back=(37,641,102,26), threshold=0.8, method="Template matching", file="./tasks/Chess/c/c_experience.png")
	# 打开阵容预设 
	I_OPEN_LINEUP = RuleImage(roi_front=(85,15,137,43), roi_back=(264,12,47,44), threshold=0.8, method="Template matching", file="./tasks/Chess/c/c_open_lineup.png")
	# 商店刷新 
	I_REFRESH = RuleImage(roi_front=(1169,419,65,64), roi_back=(1169,419,65,64), threshold=0.8, method="Template matching", file="./tasks/Chess/c/c_refresh.png")
	#  
	I_REFRESH_NOT_GOLD = RuleImage(roi_front=(1169,419,65,64), roi_back=(1169,419,65,64), threshold=0.8, method="Template matching", file="./tasks/Chess/c/c_refresh_not_gold.png")
	#  
	I_SKIP = RuleImage(roi_front=(1148,39,77,22), roi_back=(1148,39,77,22), threshold=0.8, method="Template matching", file="./tasks/Chess/c/c_skip.png")
	#  
	I_SHIKIGAMI_SPECIFICS = RuleImage(roi_front=(1215,106,44,46), roi_back=(1215,106,44,46), threshold=0.8, method="Template matching", file="./tasks/Chess/c/c_shikigami_specifics.png")
	#  
	I_CHECK_MARKET = RuleImage(roi_front=(1206,319,35,31), roi_back=(1206,319,35,31), threshold=0.8, method="Template matching", file="./tasks/Chess/c/c_check_market.png")
	#  
	I_CHESS_EXIT = RuleImage(roi_front=(12,14,48,38), roi_back=(12,14,48,38), threshold=0.8, method="Template matching", file="./tasks/Chess/c/c_chess_exit.png")
	#  
	I_CHESS_EXIT_CONFIRM = RuleImage(roi_front=(716,409,88,45), roi_back=(716,409,88,45), threshold=0.8, method="Template matching", file="./tasks/Chess/c/c_chess_exit_confirm.png")
	#  
	I_CHESS_EXIT_CANCEL = RuleImage(roi_front=(478,409,88,45), roi_back=(478,409,88,45), threshold=0.8, method="Template matching", file="./tasks/Chess/c/c_chess_exit_cancel.png")


	# Ocr Rule Assets
	# 商店式神名称5 
	O_SHIKIGAMI_GOLD_5 = RuleOcr(roi=(501,261,21,34), area=(501,261,21,34), mode="Single", method="Default", keyword="", name="shikigami_gold_5")
	# 商店式神名称4 
	O_SHIKIGAMI_GOLD_4 = RuleOcr(roi=(688,261,21,34), area=(688,261,21,34), mode="Single", method="Default", keyword="", name="shikigami_gold_4")
	# 商店式神名称3 
	O_SHIKIGAMI_GOLD_3 = RuleOcr(roi=(875,261,21,34), area=(875,261,21,34), mode="Single", method="Default", keyword="", name="shikigami_gold_3")
	# 商店式神名称2 
	O_SHIKIGAMI_GOLD_2 = RuleOcr(roi=(1062,261,21,34), area=(1062,261,21,34), mode="Single", method="Default", keyword="", name="shikigami_gold_2")
	# 商店式神名称1 
	O_SHIKIGAMI_GOLD_1 = RuleOcr(roi=(1249,261,21,34), area=(1249,261,21,34), mode="Single", method="Default", keyword="", name="shikigami_gold_1")
	# 当前等级 
	O_LEVEL = RuleOcr(roi=(131,680,47,30), area=(131,680,47,30), mode="Single", method="Default", keyword="", name="level")
	# 当前回目 
	O_ROUND = RuleOcr(roi=(469,0,67,30), area=(469,0,67,30), mode="Single", method="Default", keyword="", name="round")
	# 当前金币 
	O_GOLD = RuleOcr(roi=(1198,640,43,32), area=(1198,640,43,32), mode="Digit", method="Default", keyword="", name="gold")
	# 当前环节 
	O_CHESS_MODE = RuleOcr(roi=(741,0,32,28), area=(741,0,32,28), mode="Single", method="Default", keyword="", name="chess_mode")
	#  
	O_ROUND_2 = RuleOcr(roi=(507,0,62,30), area=(507,0,62,30), mode="Single", method="Default", keyword="", name="round_2")
	#  
	O_CHESS_MODE_2 = RuleOcr(roi=(706,2,32,28), area=(706,2,32,28), mode="Single", method="Default", keyword="", name="chess_mode_2")
	#  
	O_BADGE_AREA = RuleOcr(roi=(181,650,945,46), area=(181,650,945,46), mode="Single", method="Default", keyword="", name="badge_area")
	#  
	O_COIN = RuleOcr(roi=(141,659,87,25), area=(141,659,87,25), mode="Single", method="Default", keyword="", name="coin")
	#  
	O_NOW_TIME = RuleOcr(roi=(768,0,32,28), area=(768,0,32,28), mode="Single", method="Default", keyword="", name="now_time")
	#  
	O_HEALTH_1 = RuleOcr(roi=(1186,76,31,24), area=(1186,76,31,24), mode="Single", method="Default", keyword="", name="health_1")
	#  
	O_HEALTH_2 = RuleOcr(roi=(1186,138,31,24), area=(1186,138,31,24), mode="Single", method="Default", keyword="", name="health_2")
	#  
	O_HEALTH_3 = RuleOcr(roi=(1186,200,31,24), area=(1186,200,31,24), mode="Single", method="Default", keyword="", name="health_3")
	#  
	O_HEALTH_4 = RuleOcr(roi=(1186,262,31,24), area=(1186,262,31,24), mode="Single", method="Default", keyword="", name="health_4")
	#  
	O_HEALTH_5 = RuleOcr(roi=(1186,324,31,24), area=(1186,324,31,24), mode="Single", method="Default", keyword="", name="health_5")
	#  
	O_HEALTH_6 = RuleOcr(roi=(1186,386,31,24), area=(1186,386,31,24), mode="Single", method="Default", keyword="", name="health_6")
	#  
	O_HEALTH_7 = RuleOcr(roi=(1186,448,31,24), area=(1186,448,31,24), mode="Single", method="Default", keyword="", name="health_7")
	#  
	O_HEALTH_8 = RuleOcr(roi=(1186,510,31,24), area=(1186,510,31,24), mode="Single", method="Default", keyword="", name="health_8")


